version: "3"

services:
  db:
    container_name: database
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres_data:/var/lib/postgresql
    ports:
      - 3308:3306

  backend:
    container_name: backend
    tty: true
    depends_on:
      - db
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8000 -b '0.0.0.0'"

  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    container_name: web
    volumes:
      - ./web/app:/usr/src/app
    command: sh -c "npm run dev"
    ports:
      - "3000:3000"
