FROM ruby:3.1.2
#RUN apt-get update -qq \
#   && apt-get install -y nodejs postgresql-client npm \
#  && rm -rf /var/lib/apt/lists/* \
# && npm install --global yarn
#WORKDIR /app
#COPY Gemfile /app/Gemfile
#COPY Gemfile.lock /app/Gemfile.lock
#RUN bundle install

# Add a script to be executed every time the container starts.
#COPY entrypoint.sh /usr/bin/
#RUN chmod +x /usr/bin/entrypoint.sh
#ENTRYPOINT ["entrypoint.sh"]
#EXPOSE 3000

# Configure the main process to run when running the image
#CMD ["rails", "server", "-b", "0.0.0.0"]

ENV LANG=C.UTF-8 \
    TZ=Asia/Tokyo

RUN apt update -qq && apt install -y postgresql-client

RUN mkdir /app
WORKDIR /app
COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

RUN gem install bundler
RUN bundle install
